from .joy_caption_two_node import  NODE_CLASS_MAPPINGS as NODES_CLASS_JOY_CAPTION_TWO, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_JOY_CAPTION_TWO

NODE_CLASS_MAPPINGS = {**NODES_CLASS_JOY_CAPTION_TWO,
                       }

NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_JOY_CAPTION_TWO,
                              }